name: github-workflow
on:
 push
jobs:
 build-trigger:
   runs-on: ubuntu-latest
   steps:
    - name: context-workflow
      run: |
        echo "git: ${{ github }}"
        echo "action: ${{ github.action }}"
        echo "action_path: ${{ github.action_path }}"
        echo "action_ref: ${{ github.action_ref }}"
        echo "action_repository: ${{ github.action_repository }}"
        echo "user_name: ${{ github.actor }}"
        echo "user_name_id: ${{ github.actor_id }}"
        echo "api_url: ${{ github.api_url }}"
        echo "action_status: ${{ github.action_status }}"

        echo "base_ref: ${{ github.base_ref }}"

        echo "env ${{ github.env }}"
        echo "event ${{ github.event }}"
        echo "event_name ${{ github.event_name }}"
        echo "event_path ${{ github.event_path }}"
        
        echo "url_graphql ${{ github.graphql_url }}"
        echo "source_branch ${{ github.head_ref }}" 

        echo "job: ${{ github.job }}"

        echo "path: ${{ github.path }}"

        echo "ref_branch/tag: ${{ github.ref }}"
        echo "ref_branch_name: ${{ github.ref_name }}"
        echo "branch_protecte/not: ${{ github.ref_protected }}"
        echo "reference_type: ${{ github.ref_type }}"
        echo "repository_name: ${{ github.repository }}"
        echo "repository_id: ${{ github.repository_id }}"
        echo "repository_owner: ${{ github.repository_owner }}"
        echo "repository_owner_id: ${{ github.repository_owner_id }}"
        echo "repo_url: ${{ github.repositoryUrl }}"
        echo "no_of_days: ${{ github.retention_days }}"
        echo "run_id: ${{ github.run_id }}"
        echo "run_number: ${{ github.run_number }}"
        echo "no_of_attempt: ${{ github.run_attempt }}" 

        echo "secret_source_used/not: ${{ github.secret_source }}"
        echo "server_url: ${{ github.server_url }}"
        echo "sha_code: ${{ github.sha }}"

        echo "token: ${{ github.token }}"
        echo "trigger_name: ${{ github.triggering_actor }}"

        echo "workflow_name: ${{ github.workflow }}"
        echo "workflow_ref_path: ${{ github.workflow_ref }}"
        echo "workflow_sha: ${{ github.workflow_sha }}"
        echo "workspace: ${{ github.workspace }}"
        
        
        
        

   
        
        
        
        
       
      
