name: github-workflow
on:
 push
jobs:
 build-trigger:
   runs-on: ubuntu-latest
   steps:
    - name: context-workflow
      run: |
        echo "git ${{ github }}"
        echo "action ${{ github.action }}"
        echo "action_path ${{ github.action_path }}"
        echo "action_ref ${{ github.action_ref }}"
        echo "action_repository ${{ github.action_repository }}"
        echo "user_name: ${{ github.actor }}"
        echo "user_name_id ${{ github.actor_id }}"
        echo "api_url ${{ github.api_url }}"
        echo "action_status ${{ github.action_status }}"

        echo "base_ref ${{ github.base_ref }}"
        
        echo "env ${{ github.env }}"
        echo "event ${{ github.event }}"
        echo "event_name ${{ github.event_name }}"
        echo "event_path ${{ github.event_path }}"
        
        
        echo "reference_name: ${{ github.ref }}"
        echo "sha_code: ${{ github.sha }}"
        echo "user_name: ${{ github.actor }}"
        echo "workflow_name: ${{ github.workflow }}"
        echo "run_id: ${{ github.run_id }}"
        echo "run_number: ${{ github.run_number }}"
